# Generated by Django 4.1.7 on 2023-02-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_costumer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='costumer',
            new_name='customer',
        ),
    ]
